### PR TITLE
Fix compiling static attributes

### PR DESCRIPTION
**Pull request by rodion-k**

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Hi, this will revert static expressions, this should rather be:
```php
if ($attribute->hasStaticMember('value') || $attribute->getValue() instanceof TextElement)
```

**Comment by rodion-k** [comment]
As far as I understand, based on [AttributeNodeCompiler](https://github.com/phug-php/compiler/blob/989ca2b17794eff3c6dbc1fd496d1f145fd7cce6/src/Phug/Compiler/NodeCompiler/AttributeNodeCompiler.php#L26), $attribute->getValue() can be `TextElement` or `ExperssionElement`.
Can you give an example of pug code then attribute value will be string?

**Comment by kylekatarnls** [comment]
`$attribute` is not a string, but `hasStaticMember('value')` does not test that, it tests `$attribute->value`.

**Comment by rodion-k** [comment]
Furthermore, compiler already checks [hasStaticValue](https://github.com/phug-php/compiler/blob/989ca2b17794eff3c6dbc1fd496d1f145fd7cce6/src/Phug/Compiler/NodeCompiler/AttributeNodeCompiler.php#L30), so we can only check instanceof TextElement

**Comment by rodion-k** [comment]
I'm talking about $attribute->value will never be a string

**Comment by kylekatarnls** [comment]
It might happen when hooking the compile node event or if you have custom(s) assignment_handlers. You can manually add/yield an attribute in such events or interceptors:
```php
$attribute = new AttributeElement('src', '/foo/bar.png');
$img->getAttributes()->attach($attribute);
```
So removing the hasStaticMember can cause a regression in existing apps.

**Comment by kylekatarnls** [comment]
Sorry for the delay. I miss the last commit. I will check this change in phug/phug and I think it will be fine.

**Comment by kylekatarnls** [comment]
Tested on phug/phug and it breaks the `attributes_mapping` option.

@rodion-k Can you give me an example of what exactly would be fixed by this PR. A complete minimal case of PHP rendering with the Pug code and actual vs. expected output.

Else it will still be a no-go for now.

**Comment by rodion-k** [comment]
Pug:
```
$renderer = new Phug\Renderer(['debug' => false]);
$renderer->compile('input.form-control(name="foo" value="bar")');
```

Actual:
```
# $pugModule init
<input<?= (is_bool($_pug_temp = $pugModule['Phug\Formatter\Format\BasicFormat::attributes_assignment']([], ['class' => 'form-control', 'name' => 'foo'], ['value' => 'bar'])) ? var_export($_pug_temp, true) : $_pug_temp) ?> />
```

Expected
```
<input class="form-control" name="foo" value="bar" />
```

**Comment by kylekatarnls** [comment]
@rodion-k this case should not returns static HTML code, it seems static but it's dynamic under the hood since:

Options can intercept attributes with events or `attributes_mapping`. Class can be merged. You can have some extension that add a `class="foo"` attribute to `input` tag. Then it should not render `class="foo" class="form-control"` but it should render `class="foo form-control"`.

So make class compiling into static HTML would many features no longer available.

The `compile` method is public only to ease integration with framework caching, it aims to produce a PHP code able to render the HTML but it's not meant to get some predictable code and less likely HTML ready-to-use code.

What is your high level goal in this fix?

**Comment by rodion-k** [comment]
The goal is performance. While profiling I found thousands calls of $pugModule functions.
image

And then realized what part of that they do can be done at compile time. If we should always run `attribute_assigment` module, why there is condition `hasNonStaticAttributes` in [this line](https://github.com/phug-php/formatter/blob/1d7530538d03e33727ae6ab323fcc0ebf3214474/src/Phug/Formatter/Format/XmlFormat.php#L333)?

**Comment by kylekatarnls** [comment]
hasNonStaticAttributes will be taken into account for example when hooks (programmatically created element, options or interceptors) provides static attributes.

```php
$attribute = new AttributeElement('width', '12');
$iframe = new MarkupElement('iframe');
$iframe->getAttributes()->attach($attribute);

$formatter = new Formatter();

echo $formatter->format($iframe);
```

This will output `<iframe width="12"></iframe>` (without rendering). This is a very particular case. With the whole process from a pug code input to the compiled output you should always fall in the dynamic case as it does for pugjs.

**Comment by kylekatarnls** [comment]
It's an hard decision, but I cannot merge this PR as is. It would need a condition such as "no hook and no attributes_mapping option set".

**Pull request closed without merging**
